### ISSUE TITLE
EM convergence

### ISSUE THREAD

**Issue by gkocker** [vicow/linear-regression-mixtures#1]
Hi Victor,

Thank you for putting this up! I was just playing around with the example yesterday and noticed that the estimation would often not converge (for example, first plot below). I found what I believe are a couple bugs in _expectation_maximization in linear-regressions-mixture.py:

line 116: probabilities is missing factor of 1/np.sqrt(2*np.pi) (this doesn't seem to be a big deal)

line 136: The maximization for beta has an extra factor of pi in it. According to my copy of Bishop, it should be just beta = N / np.sum(gamma*err). Implementing that change gives me the results in the second plot below.

Best,
Gabe

![ex_bad](https://cloud.githubusercontent.com/assets/1170566/19527609/7e98d0f8-95dd-11e6-82f1-ec2e8da17adb.png)

![ex_good](https://cloud.githubusercontent.com/assets/1170566/19527610/7e9d6d02-95dd-11e6-8d6c-026f7483f59a.png)

**Comment by victorkristof** [comment]
Hi Gabe, 

Thank you for noticing and describing this bug 3 years ago :) Here is my answer - better late than never!

I implemented the update for `beta` in a slightly different way than described in Bishop. I wanted to have one `beta_k` per component, instead of one shared `beta`. But it doesn't work (I screwed up somewhere I guess), as you correctly spotted. So I'll use your suggestion, i.e., having one shared `beta` for all components.

Thank you again and I hope this helps!

Cheers,
Victor.
